podSpec:
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  containers:
    # ToDo: move to native report:
    # env:E2E_EXTRA_ARGS=--progress-report-url=http://localhost:8099/progress
    - name: report-progress
      image: quay.io/mrbraga/openshift-tests-provider-cert:latest
      imagePullPolicy: Always
      command:
      - /bin/sh
      - /ocp-conformance/report-progress.sh
      volumeMounts:
      - mountPath: /tmp/sonobuoy/results
        name: results
sonobuoy-config:
  driver: Job
  plugin-name: openshift-tests-provider-cert
  result-format: junit
spec:
  name: plugin
  image: quay.io/mrbraga/openshift-tests-provider-cert:latest
  imagePullPolicy: Always
  env:
    # ToDo: native report is not working, using custom container
    #- name: E2E_EXTRA_ARGS
    #  value: --progress-report-url=http://localhost:8099/progress

    # Example: select suite to run
    #- name: E2E_SUITE
    #  value: kubernetes/conformance

    # Example: keep the focus on Conformance tests only.
    #- name: E2E_FOCUS
    #  value: \[Conformance\]

    # Example:Run custom test file (should be included on image)
    #- name: CUSTOM_TEST_FILE
    #  value: level1.txt

    # Example:Use internal parser/filter to run jobs
    #- name: CUSTOM_TEST_FILTER_SIG
    #  value: sig-storage

    # Example: Filter tests from all suite by string pattern
    #- name: CUSTOM_TEST_FILTER_STR
    #  value: \[sig-cli\]

  command:
    - /bin/sh
    - /ocp-conformance/run.sh
  resources: {}
  volumeMounts:
  - mountPath: /tmp/sonobuoy/results
    name: results

