config-map:
  ytt-transform.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.all
    #@overlay/match-child-defaults expects="0+"
    ---
    items:
      #@overlay/match by=overlay.all
      - items:
        #@overlay/match by=overlay.map_key("status")
        #@overlay/remove via=lambda left, right: right
        - status: skipped
podSpec:
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
  volumes:
    - name: shared
      emptyDir: {}
  containers:
    #- name: postprocessing
    #  image: schnake/postprocessor:v0
    #  command: ["/sonobuoy-processor"]
    #  volumeMounts:
    #  - mountPath: /tmp/sonobuoy/results
    #    name: results
    - name: report-progress
      image: quay.io/ocp-cert/openshift-tests-provider-cert:devel
      imagePullPolicy: Always
      priorityClassName: system-node-critical
      command: ["./report-progress.sh"]
      volumeMounts:
      - mountPath: /tmp/sonobuoy/results
        name: results
      - mountPath: /tmp/shared
        name: shared
      env:
        - name: CERT_LEVEL
          value: "0"
        - name: ENV_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ENV_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ENV_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
sonobuoy-config:
  driver: Job
  plugin-name: openshift-kube-conformance
  result-format: junit
  description: The end-to-end tests maintained by Kubernetes to certify the platform.
  source-url: https://github.com/openshift/provider-certification-tool/blob/mvp/tools/plugins/openshift-kube-conformance.yaml
  skipCleanup: true
spec:
  name: plugin
  image: quay.io/ocp-cert/openshift-tests-provider-cert:devel
  imagePullPolicy: Always
  priorityClassName: system-node-critical
  volumeMounts:
  - mountPath: /tmp/sonobuoy/results
    name: results
  - mountPath: /tmp/shared
    name: shared
  env:
    - name: CERT_LEVEL
      value: "0"
    - name: ENV_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: ENV_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: ENV_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
