config-map:
  ytt-transform.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.all
    #@overlay/match-child-defaults expects="0+"
    ---
    items:
      #@overlay/match by=overlay.all
      - items:
          #@overlay/match by=overlay.all
          - items:
            #@overlay/match by=overlay.subset({"status": "skipped"})
            #@overlay/remove
            -

podSpec:
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
  volumes:
    - name: shared
      emptyDir: {}
  containers:
    - name: postprocessing
      image: quay.io/ocp-cert/openshift-tests-provider-cert:devel
      imagePullPolicy: Always
      command: ["/usr/bin/sonobuoy-processor"]
      volumeMounts:
      - mountPath: /tmp/sonobuoy/results
        name: results
    - name: report-progress
      image: quay.io/ocp-cert/openshift-tests-provider-cert:devel
      imagePullPolicy: Always
      priorityClassName: system-node-critical
      command: ["./report-progress.sh"]
      volumeMounts:
      - mountPath: /tmp/sonobuoy/results
        name: results
      - mountPath: /tmp/shared
        name: shared
      env:
        - name: CERT_LEVEL
          value: "1"
        - name: ENV_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ENV_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ENV_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
sonobuoy-config:
  driver: Job
  plugin-name: openshift-conformance-validated
  result-format: manual
  description: The end-to-end tests maintained by OpenShift to certify the Provider running the OpenShift Container Platform.
  source-url: https://github.com/openshift/provider-certification-tool/blob/mvp/tools/plugins/openshift-conformance-validated.yaml
  skipCleanup: true
spec:
  name: plugin
  image: quay.io/ocp-cert/openshift-tests-provider-cert:devel
  imagePullPolicy: Always
  priorityClassName: system-node-critical
  volumeMounts:
  - mountPath: /tmp/sonobuoy/results
    name: results
  - mountPath: /tmp/shared
    name: shared
  env:
    - name: CERT_LEVEL
      value: "1"
    - name: DEV_MODE_COUNT
      value: "10"
    - name: ENV_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: ENV_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: ENV_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
